package alexblog::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'alexblog::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:perl',
        user => 'root',
        password => 'admin',
        AutoCommit => q{1},
    }
);

=head1 NAME

alexblog::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<alexblog>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<alexblog::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

amira

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
